Add npm scripts, update instructions
miranj/craft-boilerplate pull request #23
Opened 2022-06-10 12:47 UTC by anita-chouhan

Fixes #22

2022-06-10 13:12 UTC, rungta requested changes

2022-06-10 13:12 UTC, rungta commented on README.md.default
No need for Step 3 _Run Gulp_ now.

2022-06-13 07:49 UTC, anita-chouhan commented on README.md.default
Done.

2022-06-13 10:12 UTC, rungta approved these changes

2022-06-13 10:17 UTC, merged