Add date range component
miranj/craft-boilerplate pull request #39
Opened 2022-10-13 08:10 UTC by anita-chouhan

Fixes #30 

Fixed one error that I found while testing.
<img width="935" alt="Screenshot 2022-10-13 at 1 39 36 PM" src="https://user-images.githubusercontent.com/30666052/195540063-4bb8955e-4104-4b46-a292-3e38705e62d8.png">

2022-10-26 10:00 UTC, rungta requested changes

2022-10-26 10:00 UTC, rungta commented on templates/_components/_period.twig
> +  @param  summarize     {boolean}    Whether to show summarize date range (default: false)
Whether to ~show~ summarize the date range

2022-11-03 13:45 UTC, anita-chouhan commented on templates/_components/_period.twig
> +  @param  summarize     {boolean}    Whether to show summarize date range (default: false)
Updated the comment.

2022-11-03 15:02 UTC, rungta approved these changes

2022-11-07 07:29 UTC, merged