Add meta information component
miranj/craft-boilerplate pull request #41
Opened 2022-10-13 08:42 UTC by anita-chouhan

Fixes #31

2022-10-26 10:10 UTC, rungta requested changes

2022-10-26 10:10 UTC, rungta commented on templates/_components/metaInfo.twig
> +    alt: i.title ?? '',
This is an unused attribute. Remove.

2022-11-03 13:22 UTC, anita-chouhan commented on templates/_components/metaInfo.twig
> +    alt: i.title ?? '',
Removed `alt`.

2022-11-03 15:00 UTC, rungta approved these changes

2022-11-07 07:30 UTC, merged