Add JSON-LD for index page
miranj/craft-boilerplate pull request #62
Opened 2023-01-19 13:21 UTC by anita-chouhan

2023-01-19 13:41 UTC, rungta requested changes

2023-01-19 13:41 UTC, rungta commented on templates/_schemas/details/blog.twig
> +{% extends "_schemas/details/_index" %}
The `blog` template will be project specific. Should not include in the boilerplate.

2023-01-20 05:22 UTC, anita-chouhan commented on templates/_schemas/details/blog.twig
> +{% extends "_schemas/details/_index" %}
Okay. Removed.

2023-01-24 11:57 UTC, rungta approved these changes

2023-01-25 05:34 UTC, merged