Add routing templates for Index pages
miranj/craft-boilerplate pull request #80
Opened 2023-11-23 03:08 UTC by pl-mnm

2023-11-23 08:59 UTC, rungta requested changes

2023-11-23 08:59 UTC, rungta commented on src/Module.php
> +    public function onSectionDefineBehaviors(DefineBehaviorsEvent $event)
I don’t think the `SectionRouterBehavior` class has been imported, or the `onSectionDefineBehaviors` property is being invoked below.

2025-03-18 03:01 UTC, pl-mnm commented
@rungta fixed some things and updated this PR so we can merge it into the next release. Please take a look.

2025-04-07 13:52 UTC, rungta requested changes

2025-04-07 13:52 UTC, rungta commented on templates/_views/indexes/_default.twig
Let’s not introduce the old index default template at the moment, and keep rendering for a separate PR.

2025-04-07 15:31 UTC, merged